### ISSUE TITLE
Create a webhook notification for promotion completed

### ISSUE THREAD

**Issue by GiriDandu** [lookout/deploydb#74]
Promotion completed webhook is described in deploydb internal page. See below

http://hackers.lookout.com/deploydb/internals.html#_flow_diagram

**Comment by maheshkelkar** [comment]
@rtyler I think we should call this as promotion "verified" instead of completed. 

In case of webhook for deployment:
- "completed" means that deployment is all set up correctly and ready to run the validations
- "verified" means that we are done evaluating the artifact in given deployment (either susccess or failure);

**Comment by rtyler** [comment]
"verification" is commonly used to in a positive sense (i.e. "this has been verified" is usually interptered to mean "this is correct").

I think completed is the most reasonable terminology to use still, because it's only going to declare that we've completed whatever process we needed to execute in order to verify the deployment.

**Comment by maheshkelkar** [comment]
In that case I think we are not using consistent terminologies for deployment and promotions.

E.g. 
- deployment completed, eventhough signifies end of rundeck's role, it does not signify we're done with this deployment, because verification follows the completion
- in case of promotions, promotions complete, not only signify the end of PA's role, but it also signifies that we are done with this promotion altogether.
- I agree "verified" is used in positive sense, hence I we should have used verified & failed; but you prefered verified w/status to indicate the result

**Comment by rtyler** [comment]
> deployment completed, eventhough signifies end of rundeck's role, it does not signify we're done with this deployment, because verification follows the completion

This is incorrect. I believe you're interpreting "Deployment" as a concept far larger than it actually is. The act of deployment is in fact completed when the "orchestrator" (e.g. Rundeck) has finished its task(s).

> in case of promotions, promotions complete, not only signify the end of PA's role, but it also signifies that we are done with this promotion altogether.

Forget the concept of PA entirely. For a single promotion as defined, when I get a result then that promotion is in fact done. Whether that's a simple status checking promotion or a Jenkins job which will report some results back into DeployDB.

Note that this ticket is about the completion of a single promotions as written.


> I agree "verified" is used in positive sense, hence I we should have used verified & failed; but you prefered verified w/status to indicate the result

I do not want to configure two separate webhook destinations for the positive and the negative results. All I want to know from a webhook consumer point of view (e.g. hubot plugin) is that a promotion is done.

----

@GiriDandu I don't actually remember why or if we actually needed this task for 0.1.0. As far as I can tell we can punt it into the backlog

**Comment by GiriDandu** [comment]
@rtyler I was about to do this work. Don't we need this for test automation to glue into CI/CD

**Comment by rtyler** [comment]
@GiriDandu this webhook specifically I think is "nice to have" but not required. I could be wrong of course :)

**Comment by GiriDandu** [comment]
@rtyler let me finish this and make @tsullivan happy.  This will also allows end-to-end testing for all the involved services in CI/CD
